var RESEARCH_DATA = [
  {
    id: 1, category: "materials",
    title: "CQDs Introduction",
    authors: "",
    journal: "Nature. Mater.",
    journal: "Chem. Rev.",
    journal: "Adv. Mater.",
    year: "",
    image: "research/product1.png",
    description: "Fundamental concepts of colloidal quantum dots: quantum confinement effect, energy level engineering, and their significance in next-generation display technologies. The 2023 Nobel Prize in Chemistry was awarded for the discovery and synthesis of quantum dots.",
    tags: [top-journal],
    doi: ""
  },
  {
    id: 2, category: "materials",
    title: "Core-shell Structures",
    authors: "",
    journal: "Adv.Mat",
    year: "2024",
    image: "research/product2.png",
    description: "Advanced core-shell nanostructure design including gradient alloy shells and lattice contraction engineering. Surface modification strategies with tailored ligand chemistry (oleic acid, zinc acetate, TGA) to achieve quantum yield up to 85%.",
    tags: [top-journal],
    doi: ""
  },
  {
    id: 3, category: "materials",
    title: "Core-shell Synthesis",
    authors: "Xijian Duan",
    journal: "Adv.Mat",
    year: "2024",
    image: "research/product3.png",
    description: "Systematic development of core-shell QD synthesis protocols: InCl₃ + OAm → In(OAm)₃ precursor route, TMS₃P as phosphorus source, controlled shell growth for InP-based QDs with high reproducibility and scalability.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 4, category: "materials",
    title: "Green-emitting InP-based QDs",
    authors: "",
    journal: "Adv.Fun.Mat",
    year: "2021",
    image: "research/product4.png",
    description: "Highly efficient green-emitting InP-based quantum dots with narrow emission linewidth. Comprehensive characterization including temperature-dependent PL spectroscopy, STEM imaging, and particle size distribution analysis.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 5, category: "materials",
    title: "Red-emitting InP-based QDs",
    authors: "",
    journal: "ACS Appl.Mat",
    year: "2023",
    image: "research/product5.png",
    description: "Record-performance red-emitting InP quantum dots achieving outstanding device efficiency. Advanced TEM characterization and PL spectral analysis demonstrate the structural and optical quality of the synthesized QDs.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 6, category: "materials",
    title: "Blue-emitting InP-based QDs",
    authors: "",
    journal: "Adv.Opt.Mater",
    year: "2022",
    image: "research/product6.png",
    description: "Record EQE of 2.6% for blue-emitting InP-based quantum dots — a breakthrough in cadmium-free blue QD technology. Comprehensive optical and structural characterization validate the device performance.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 7, category: "materials",
    title: "Blue-emitting ZnSeTe-based QDs",
    authors: "Lei Jin",
    journal: "Adv.Opt.Mater",
    year: "2023",
    image: "research/product7.png",
    description: "Blue-emitting ZnSeTe-based colloidal quantum dots with EQE ~1.2%. A novel material system expanding the palette of cadmium-free QDs for full-color display applications.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 8, category: "optics",
    title: "Exploring CQDs at Single-Dot Level",
    authors: "Mi Gu",
    journal: "",
    year: "",
    image: "research/product8.png",
    description: "Single-particle spectroscopy studies revealing fundamental photophysics of individual colloidal quantum dots: blinking dynamics, spectral diffusion, and emission intermittency at the nanoscale.",
    tags: [],
    doi: ""
  },
  {
    id: 9, category: "devices",
    title: "QLEDs & Impedance Spectroscopy",
    authors: "Jingrui Ma",
    journal: "Appl.Phys",
    year: "2024",
    image: "research/product9.png",
    description: "In-depth impedance spectroscopy analysis of QLED devices to elucidate charge injection, transport, and recombination mechanisms. Provides critical insights for device optimization and performance improvement.",
    tags: ["top-journal"],
    doi: ""
  },
   {
    id: 15, category: "optics",
    title: "QLED Analysis & LEDA Software",
    authors: "Dr. Guanding Mei",
    journal: "Nature.Nanotechnology",
    year: "",
    image: "research/product10.png",
    description: "Advanced optical simulation framework for QLED light extraction analysis. Development of LEDA (LED Analysis) software for modeling and optimizing light outcoupling efficiency in quantum dot display architectures.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 10, category: "devices",
    title: "QDs for Display",
    authors: "PLANCK InnoTech Co.Ltd",
    journal: "",
    year: "",
    image: "research/product11.png",
    description: "Comprehensive overview of quantum dot display technologies: QDEF (on-surface), QDCF (on-edge), and next-generation Planck Innovation approaches. Collaboration ecosystem with Samsung, Planck, and industry partners.",
    tags: [],
    doi: ""
  },
  {
    id: 11, category: "devices",
    title: "QD Patterning — Selective Electrophoretic Deposition",
    authors: "",
    journal: "Nature.Comm",
    year: "2021",
    image: "research/product12.png",
    description: "High-resolution QD patterning via selective electrophoretic deposition achieving >1000 PPI — a critical step toward high-density QD-based microdisplays and full-color pixel arrays.",
    tags: [],
    doi: ""
  },
  {
    id: 12, category: "devices",
    title: "Inkjet-Printed QLEDs",
    authors: "",
    journal: "Adv.Opt.Mat",
    year: "2021",
    image: "research/product13.png",
    description: "Inkjet-printed QLED devices achieving industry-leading operational lifetime. Scalable manufacturing approach combining solution-processable QDs with precision printing technology for cost-effective large-area displays.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 13, category: "devices",
    title: "QLED Microdisplay ",
    authors: "Min Fu",
    journal: "World's 1st FHD",
    year: "",
    image: "research/product14.png",
    description: "World's first QLED microdisplay exceeding 5800 PPI — a landmark achievement in ultra-high-resolution display technology. Opens new possibilities for AR/VR, near-eye displays, and next-generation microdisplays.",
    tags: ["top-journal"],
    doi: ""
  },
  {
    id: 14, category: "devices",
    title: "Transparent QLEDs",
    authors: "",
    journal: "",
    year: "",
    image: "research/product15.png",
    description: "Transparent quantum dot light-emitting diodes with high visible transmittance (>70%). Enables novel applications in see-through displays, smart windows, and augmented reality interfaces.",
    tags: [],
    doi: ""
  },
  {
    id: 16, category: "waveguide",
    title: "AR Waveguide",
    authors: "",
    journal: "",
    year: "",
    image: "",
    description: "Coming Soon",
    tags: ["coming-soon"],
    doi: ""
  }
];
